### ISSUE TITLE
V2 Early Access - some installer cosmetics

### ISSUE THREAD

**Issue by gOOvER** [Moonlight-Panel/Moonlight#376] opened 2024-04-10 13:52 UTC
### Current Behavior

The installer is really nice, but have some cosmetic "Bugs"

### Expected Behavior

See Steps to reproduce

### Steps to Reproduce

```
Running installer
Updating installer
rm: cannot remove '/tmp/Installer': No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  103M  100  103M    0     0  44.4M      0  0:00:02  0:00:02 --:--:-- 44.4M
Welcome to the Moonlight installer made by @masuowo
```
I would add a check, if dir exist, before rm:
`rm: cannot remove '/tmp/Installer': No such file or directory`

```
Node Package install:

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
                       
Paketlisten werden gelesen…
Abhängigkeitsbaum wird aufgebaut…
Statusinformationen werden eingelesen…
Die folgenden NEUEN Pakete werden installiert:
  nodejs               
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 31,6 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 196 MB Plattenplatz zusätzlich benutzt.
Holen:1 https://deb.nodesource.com/node_20.x nodistro/main amd64 nodejs amd64 20.12.1-1nodesource1 [31,6 MB]
Es wurden 31,6 MB in 1 s geholt (43,0 MB/s).
Vormals nicht ausgewähltes Paket nodejs wird gewählt.              
(Lese Datenbank ...    ⠋ Installing packages                                ing packages  
(Lese Datenbank ... 5%                                                      ⠋ Installing packages                
(Lese Datenbank ... 10%                      Installing packages                                                          
(Lese Datenbank ... 15%                        Installing packages                       
(Lese Datenbank ... 20%                       ⠋ Installing packages                        
(Lese Datenbank ... 25%                       ⠋ Installing packages                         
(Lese Datenbank ... 30%                       ⠋ Installing packages                         
(Lese Datenbank ... 35%                       ⠋ Installing packages                         
(Lese Datenbank ... 40%                       ⠋ Installing packages                         
(Lese Datenbank ... 45%                       ⠋ Installing packages                         
(Lese Datenbank ... 50%                       ⠋ Installing packages                         
(Lese Datenbank ... 55%                       ⠋ Installing packages                         
(Lese Datenbank ... 60%                       ⠋ Installing packages                         
(Lese Datenbank ... 65%                       ⠋ Installing packages                         
(Lese Datenbank ... 70%                       ⠋ Installing packages                         
(Lese Datenbank ... 75%                       ⠋ Installing packages                         
(Lese Datenbank ... 80%                       ⠋ Installing packages                         
(Lese Datenbank ... 85%                       ⠋ Installing packages                         
(Lese Datenbank ... 90%                       ⠋ Installing packages                         
(Lese Datenbank ... 95%                       ⠋ Installing packages                         
(Lese Datenbank ... 100%                      ⠋ Installing packages                         
(Lese Datenbank ... 127759 Dateien und Verzeichnisse sind derzeit installiert.)             
Vorbereitung zum Entpacken von .../nodejs_20.12.1-1nodesource1_amd64.deb ...                          
Entpacken von nodejs (20.12.1-1nodesource1) ...                                                       ⠋ Installing packages  
nodejs (20.12.1-1nodesource1) wird eingerichtet ...                                                ⠋ Installing packages                            
Trigger für man-db (2.10.2-1) werden verarbeitet ...                      stalling packages                                                      
                       ⠧ Installing packages                                Installing packages                     
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.stalling packages                        
                                                                                                                         
[ ✔️ ] NodeJS successfully installed

```
output should be go to dev>0

Same for deamon install:

```
Select the build channel you want to use:
Paketlisten werden gelesen…
Abhängigkeitsbaum wird aufgebaut…
Statusinformationen werden eingelesen…
Die folgenden zusätzlichen Pakete werden installiert:
  aspnetcore-runtime-7.0 aspnetcore-targeting-pack-7.0 dotnet-apphost-pack-7.0
  dotnet-host-7.0 dotnet-hostfxr-7.0 dotnet-runtime-7.0
  dotnet-targeting-pack-7.0 dotnet-templates-7.0 liblttng-ust-common1
  liblttng-ust-ctl5 liblttng-ust1 netstandard-targeting-pack-2.1-7.0
Die folgenden NEUEN Pakete werden installiert:
  aspnetcore-runtime-7.0 aspnetcore-targeting-pack-7.0 dotnet-apphost-pack-7.0
  dotnet-host-7.0 dotnet-hostfxr-7.0 dotnet-runtime-7.0 dotnet-sdk-7.0
  dotnet-targeting-pack-7.0 dotnet-templates-7.0 liblttng-ust-common1
  liblttng-ust-ctl5 liblttng-ust1 netstandard-targeting-pack-2.1-7.0
0 aktualisiert, 13 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 135 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 488 MB Plattenplatz zusätzlich benutzt.
Holen:1 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 dotnet-host-7.0 amd64 7.0.117-0ubuntu1~22.04.2 [179 kB]
Holen:2 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 dotnet-hostfxr-7.0 amd64 7.0.117-0ubuntu1~22.04.2 [164 kB]
Holen:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 liblttng-ust-common1 amd64 2.13.1-1ubuntu1 [27,1 kB]
Holen:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 liblttng-ust-ctl5 amd64 2.13.1-1ubuntu1 [77,9 kB]
Holen:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 liblttng-ust1 amd64 2.13.1-1ubuntu1 [190 kB]
Holen:6 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 dotnet-runtime-7.0 amd64 7.0.117-0ubuntu1~22.04.2 [24,5 MB]
Holen:7 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 aspnetcore-runtime-7.0 amd64 7.0.117-0ubuntu1~22.04.2 [7.824 kB]
Holen:8 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 aspnetcore-targeting-pack-7.0 amd64 7.0.117-0ubuntu1~22.04.2 [1.588 kB]
Holen:9 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 dotnet-apphost-pack-7.0 amd64 7.0.117-0ubuntu1~22.04.2 [3.757 kB]
Holen:10 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 dotnet-targeting-pack-7.0 amd64 7.0.117-0ubuntu1~22.04.2 [2.751 kB]
Holen:11 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 dotnet-templates-7.0 amd64 7.0.117-0ubuntu1~22.04.2 [2.869 kB]
Holen:12 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 netstandard-targeting-pack-2.1-7.0 amd64 7.0.117-0ubuntu1~22.04.2 [1.406 kB]
Holen:13 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 dotnet-sdk-7.0 amd64 7.0.117-0ubuntu1~22.04.2 [89,5 MB]
Es wurden 135 MB in 2 s geholt (76,5 MB/s).
Vormals nicht ausgewähltes Paket dotnet-host-7.0 wird gewählt.        
(Lese Datenbank ...        ⠧ Installing dotnet sdk 7.0                                    sdk 7.0
(Lese Datenbank ... 5%                                                                   ⠧ Installing dotnet sdk 7.0        
(Lese Datenbank ... 10%                          Installing dotnet sdk 7.0                                                                     
(Lese Datenbank ... 15%                            Installing dotnet sdk 7.0                         
(Lese Datenbank ... 20%                           ⠧ Installing dotnet sdk 7.0                          
(Lese Datenbank ... 25%                           ⠧ Installing dotnet sdk 7.0                           
(Lese Datenbank ... 30%                           ⠧ Installing dotnet sdk 7.0                           
(Lese Datenbank ... 35%                           ⠧ Installing dotnet sdk 7.0                           
(Lese Datenbank ... 40%                           ⠧ Installing dotnet sdk 7.0                           
(Lese Datenbank ... 45%                           ⠧ Installing dotnet sdk 7.0                           
(Lese Datenbank ... 50%                           ⠧ Installing dotnet sdk 7.0                           
(Lese Datenbank ... 55%                           ⠧ Installing dotnet sdk 7.0                           
(Lese Datenbank ... 60%                           ⠧ Installing dotnet sdk 7.0                           
(Lese Datenbank ... 65%                           ⠧ Installing dotnet sdk 7.0                           
(Lese Datenbank ... 70%                           ⠧ Installing dotnet sdk 7.0                           
(Lese Datenbank ... 75%                           ⠧ Installing dotnet sdk 7.0                           
(Lese Datenbank ... 80%                           ⠧ Installing dotnet sdk 7.0                           
(Lese Datenbank ... 85%                           ⠧ Installing dotnet sdk 7.0                           
(Lese Datenbank ... 90%                            7.0stalling dotnet sdk 7.0                           
(Lese Datenbank ... 95%                           ⠇ Installing dotnet sdk 7.0                           
(Lese Datenbank ... 100%                          ⠇ Installing dotnet sdk 7.0                           
(Lese Datenbank ... 133590 Dateien und Verzeichnisse sind derzeit installiert.)                         
Vorbereitung zum Entpacken von .../00-dotnet-host-7.0_7.0.117-0ubuntu1~22.04.2_amd64.deb ...              
Entpacken von dotnet-host-7.0 (7.0.117-0ubuntu1~22.04.2) ...                                                           dotnet sdk 7.0
Vormals nicht ausgewähltes Paket dotnet-hostfxr-7.0 wird gewählt.                                                      ⠇ Installing dotnet sdk 7.0              
Vorbereitung zum Entpacken von .../01-dotnet-hostfxr-7.0_7.0.117-0ubuntu1~22.04.2_amd64.deb ...ling dotnet sdk 7.0                                                           
Entpacken von dotnet-hostfxr-7.0 (7.0.117-0ubuntu1~22.04.2) ...                             ⠋ I                                              
Vormals nicht ausgewähltes Paket liblttng-ust-common1:amd64 wird gewählt.                                                 ⠋ Installing dotnet sdk 7.0
Vorbereitung zum Entpacken von .../02-liblttng-ust-common1_2.13.1-1ubuntu1_amd64.deb ...            ng dotnet sdk 7.0                                                           
Entpacken von liblttng-ust-common1:amd64 (2.13.1-1ubuntu1) ...                                                     tnet sdk 7.0                 
Vormals nicht ausgewähltes Paket liblttng-ust-ctl5:amd64 wird gewählt.                                             ⠸ Installing dotnet sdk 7.0            
Vorbereitung zum Entpacken von .../03-liblttng-ust-ctl5_2.13.1-1ubuntu1_amd64.deb ...            ling dotnet sdk 7.0                                                     
Entpacken von liblttng-ust-ctl5:amd64 (2.13.1-1ubuntu1) ...                                                     tnet sdk 7.0                   
Vormals nicht ausgewähltes Paket liblttng-ust1:amd64 wird gewählt.                                              ⠹ Installing dotnet sdk 7.0            
Vorbereitung zum Entpacken von .../04-liblttng-ust1_2.13.1-1ubuntu1_amd64.deb ...            lling dotnet sdk 7.0                                                     
Entpacken von liblttng-ust1:amd64 (2.13.1-1ubuntu1) ...                                                     tnet sdk 7.0                    
Vormals nicht ausgewähltes Paket dotnet-runtime-7.0 wird gewählt.                                           ⠇ Installing dotnet sdk 7.0            
Vorbereitung zum Entpacken von .../05-dotnet-runtime-7.0_7.0.117-0ubuntu1~22.04.2_amd64.deb ...dotnet sdk 7.0                                                     
Entpacken von dotnet-runtime-7.0 (7.0.117-0ubuntu1~22.04.2) ...                             ⠹ I                                         
                           ⠼ Installing dotnet sdk 7.0                                                                    ⠹ Installing dotnet sdk 7.0
                           ⠇ Installing dotnet sdk 7.0                                    ⠼ Installing dotnet sdk 7.0                                                       
```    
                                                                                                                                     
When a Domain is used, there should be no port:
```
[ 💬 ] App URL: http://gpanel.goover.de:80
[ 💬 ] App URL: https://gpanel.goover.de:443
```

### Panel Version

V2 EA

### Daemon Version

V2 EA

### Wings Version

none

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by mxritzdev** [comment] 2024-04-10 13:53
I resolved this with just `curl https://get-moonlight.app` and then executing all comands i got from the curl

**Comment by Masu-Baumgartner** [comment] 2024-04-10 20:18
The apt output should actually been shown. Thats why i used the bash wrapper with the output handling. The issue is with how spectre is handling the output. I'll remove the status indicator for these steps i guess. The uncheck rm has been fixed in https://github.com/Moonlight-Panel/Scripts/pull/1. The ports on the app url are to indicate what protocol is running on what port

**Comment by Masu-Baumgartner** [comment] 2024-04-10 20:23
The visual glitch when installing packages via apt has been fixed in https://github.com/Moonlight-Panel/Installer/pull/6

**Closed as completed by Masu-Baumgartner** 2024-04-10 20:23 UTC
